"""Novelty detection with a character language model.

This is the system's only detection layer. A character n-gram model is fitted
exclusively on benign traffic and scores each request by its mean negative
log-likelihood per character: the less likely the string is under the profile of
normal traffic, the higher the score.

Three properties justify the choice, and all three were measured:

1. It does not use labels. The fit sees benign requests only, so the dataset's
   labels — which were generated by regex — cannot contaminate training. They
   serve to evaluate and nothing else.
2. It generalizes to unseen attacks. Since no attack example enters the fit,
   every family is detected zero-shot. A regex only catches what somebody wrote
   into it; this model catches whatever does not look like normal traffic.
3. It explains the decision. `explain` returns the least likely substring, which
   turns a number into evidence the agent can quote in an incident dossier.

Per-character normalization is deliberate: without it every long URL would score
high and the model would be a disguised length meter. The measured correlation
between score and length is -0.011.

The operating point is recall-first. The project's criterion is zero false
negatives, and false positives are acceptable because everything above the floor
is re-examined by the agents. The choice of floor lives in `calibration` and is
measured rather than asserted — see `reports/metrics.json`.
"""

from __future__ import annotations

import math
from collections import defaultdict

BOUNDARY = "\x02"
DEFAULT_MAX_ORDER = 4
DEFAULT_SMOOTHING = 0.1
DEFAULT_WINDOW = 16
# Decreasing weights by order: long context is more informative when it exists,
# but it needs backoff because most of the time it does not exist.
DEFAULT_WEIGHTS = (0.4, 0.3, 0.2, 0.1)


class UrlNoveltyModel:
    def __init__(
        self,
        max_order: int = DEFAULT_MAX_ORDER,
        smoothing: float = DEFAULT_SMOOTHING,
        weights: tuple[float, ...] = DEFAULT_WEIGHTS,
    ) -> None:
        self.max_order = max_order
        self.smoothing = smoothing
        chosen = weights[:max_order]
        total = sum(chosen)
        self.weights = tuple(weight / total for weight in chosen)

        self.context_counts: list[dict[str, int]] = [
            defaultdict(int) for _ in range(max_order)
        ]
        self.ngram_counts: list[dict[str, int]] = [
            defaultdict(int) for _ in range(max_order)
        ]
        self.vocabulary_size = 0
        self._cache: dict[str, float] = {}

    # --------------------------------------------------------------------- fit

    def fit(self, texts: list[str]) -> "UrlNoveltyModel":
        vocabulary: set[str] = set()
        padding = BOUNDARY * (self.max_order - 1)
        for text in texts:
            if not text:
                continue
            vocabulary.update(text)
            padded = padding + text
            for index in range(self.max_order):
                context_counts = self.context_counts[index]
                ngram_counts = self.ngram_counts[index]
                for position in range(self.max_order - 1, len(padded)):
                    context = padded[position - index : position]
                    context_counts[context] += 1
                    ngram_counts[context + padded[position]] += 1
        self.vocabulary_size = max(len(vocabulary), 1)
        self.freeze()
        return self

    def freeze(self) -> None:
        """Convert to plain dictionaries before serializing.

        A serialized defaultdict carries its factory along and starts growing
        again on every missing-key lookup, which in a long-running service is a
        silent memory leak.
        """
        self.context_counts = [dict(counts) for counts in self.context_counts]
        self.ngram_counts = [dict(counts) for counts in self.ngram_counts]
        self._cache = {}

    # ------------------------------------------------------------------ scoring

    def _window_nll(self, window: str) -> float:
        """NLL of one character given its context, with interpolated backoff.

        `window` holds exactly `max_order` characters: the context followed by the
        target character. Every lower-order context is a suffix of it, which makes
        the memoization exact.
        """
        cached = self._cache.get(window)
        if cached is not None:
            return cached

        char = window[-1]
        context = window[:-1]
        denominator_offset = self.smoothing * self.vocabulary_size
        mixed = 0.0
        for index, weight in enumerate(self.weights):
            suffix = context[len(context) - index :] if index else ""
            numerator = self.ngram_counts[index].get(suffix + char, 0) + self.smoothing
            denominator = (
                self.context_counts[index].get(suffix, 0) + denominator_offset
            )
            mixed += weight * (numerator / denominator)

        value = -math.log2(max(mixed, 1e-12))
        self._cache[window] = value
        return value

    def _per_char_nll(self, text: str) -> list[float]:
        padded = BOUNDARY * (self.max_order - 1) + text
        return [
            self._window_nll(padded[position - self.max_order + 1 : position + 1])
            for position in range(self.max_order - 1, len(padded))
        ]

    def score(self, text: str) -> float:
        """Mean NLL per character. Higher means less likely."""
        if not text:
            return 0.0
        return sum(self._per_char_nll(text)) / len(text)

    def explain(self, text: str, width: int = DEFAULT_WINDOW) -> str:
        """The least likely substring.

        Lets the dossier quote the exact span the model found improbable instead
        of handing the agent a bare number.
        """
        if not text:
            return ""
        if len(text) <= width:
            return text

        per_char = self._per_char_nll(text)
        running = sum(per_char[:width])
        best_total, best_start = running, 0
        for start in range(1, len(per_char) - width + 1):
            running += per_char[start + width - 1] - per_char[start - 1]
            if running > best_total:
                best_total, best_start = running, start
        return text[best_start : best_start + width]


class NoveltyDetector:
    """The URL model plus its calibrated threshold and operating-point table.

    Only the URL is scored. A variant that also modeled the user agent was
    measured and rejected: at the current operating point it loses 8.2 points of
    precision and drops PR-AUC from 0.970 to 0.761. The comparison is re-run on
    every training pass and recorded in `reports/metrics.json`.
    """

    def __init__(
        self,
        url_model: UrlNoveltyModel,
        url_threshold: float,
        calibration: dict[float, float] | None = None,
    ) -> None:
        self.url_model = url_model
        self.url_threshold = url_threshold
        # Table of {target false positive rate: threshold}, measured on the
        # calibration split. It allows moving the operating point at runtime,
        # without retraining — the right choice depends on how much triage work
        # the operation tolerates, and that is not a decision for whoever trains
        # the model.
        self.calibration = calibration or {}

    def calibrate_to(self, target_fpr: float) -> float:
        """Move the operating point to the nearest available false positive rate.

        Returns the rate actually applied, which may differ from the requested one
        when it is absent from the table.
        """
        if not self.calibration:
            return float("nan")
        chosen = min(self.calibration, key=lambda rate: abs(rate - target_fpr))
        self.url_threshold = self.calibration[chosen]
        return chosen

    def normalized_score(self, url: str) -> float:
        """Improbability in [0, 1), with 0.5 sitting at the threshold by design.

        Pinning the cutoff at 0.5 decouples the rest of the system from the
        model's NLL scale: changing the operating point, or the whole detector,
        does not require recalibrating anything downstream.
        """
        ratio = self.url_model.score(url) / max(self.url_threshold, 1e-9)
        return min(ratio / 2.0, 0.999)

    def normalized_for_fpr(self, target_fpr: float) -> float:
        """Where another operating point's threshold falls on the current scale.

        This is what allows severity to be derived from the calibration itself
        rather than from constants: "this event would still be flagged at 0.02%
        FPR" is a measured statement, "score >= 0.66 is severe" is not.
        """
        if not self.calibration:
            return float("nan")
        chosen = min(self.calibration, key=lambda rate: abs(rate - target_fpr))
        ratio = self.calibration[chosen] / max(self.url_threshold, 1e-9)
        return min(ratio / 2.0, 0.999)

    def explain(self, url: str) -> str:
        """The span of the URL that contributed most to the improbability."""
        return self.url_model.explain(url)
