"""Train the novelty detector and write the evaluation report.

The detector is a character n-gram model fitted exclusively on benign traffic. No
positive label enters training; labels serve only to evaluate. That is a
deliberate choice, not a limitation: this dataset's labels were generated by
regex, so training supervised on them yields a model that at best imitates the
regex.

Protocol:

  train IPs, benign events   ->  80% fit, 20% threshold calibration
  held-out IPs, all events   ->  evaluation

Calibrating the threshold on a slice separate from the fit avoids an optimistic
false positive rate estimate. The split is by IP because 721 of the SQLi events
come from 2 addresses — a random split would put the same payload from the same
attacker on both sides.

Two baselines are re-evaluated on every run, as evidence for why the approach is
unsupervised: the regex heuristic that labeled the dataset, and a supervised
classifier trained on those labels.

The default operating point is 0.2% FPR, chosen by measurement rather than taste:
it is where incident recall saturates at 0.9972. More permissive points recover
more attack events, but all of them inside windows already escalated — at 0.5% FPR
the dossier count rises 39% without covering one extra incident.

Usage:
    python scripts/train_model.py --target-fpr 0.002
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import average_precision_score, roc_auc_score

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.pipeline.correlator import group_by_ip_window  # noqa: E402
from app.pipeline.novelty import NoveltyDetector, UrlNoveltyModel  # noqa: E402
from app.pipeline.parser import parse_event  # noqa: E402
from scripts.baselines import regex_baseline, supervised_baseline  # noqa: E402

SEED = 20260728
TEST_FRACTION = 0.3
CALIBRATION_FRACTION = 0.2


def load_events(sample_path: Path) -> tuple[list, pd.DataFrame]:
    frame = pd.read_csv(sample_path, dtype=str, keep_default_na=False)
    events, labels, types, ips = [], [], [], []
    for record in frame.to_dict("records"):
        try:
            events.append(parse_event(record))
        except Exception:
            continue
        types.append(record["type"])
        labels.append(0 if record["type"] == "benign" else 1)
        ips.append(record["ip"])
    return events, pd.DataFrame({"ip": ips, "label": labels, "type": types})


def split_ips_by_type(meta: pd.DataFrame, seed: int) -> tuple[set[str], set[str]]:
    """Split IPs between train and test while preserving every attack class.

    A plain GroupShuffleSplit could send the only two SQLi origins to the same side
    and zero the class out of the test set. Here each type is split separately,
    starting with the rarest — the ones at risk of disappearing.
    """
    rng = np.random.default_rng(seed)
    rarity = meta[meta["type"] != "benign"]["type"].value_counts(ascending=True).index
    assigned: dict[str, str] = {}
    for type_name in [*rarity, "benign"]:
        candidates = sorted(set(meta[meta["type"] == type_name]["ip"]) - assigned.keys())
        if not candidates:
            continue
        shuffled = rng.permutation(candidates)
        cut = max(1, int(round(len(shuffled) * TEST_FRACTION))) if len(shuffled) > 1 else 0
        for ip in shuffled[:cut]:
            assigned[ip] = "test"
        for ip in shuffled[cut:]:
            assigned[ip] = "train"
    return (
        {ip for ip, side in assigned.items() if side == "train"},
        {ip for ip, side in assigned.items() if side == "test"},
    )


def calibrate(scores: np.ndarray, target_fpr: float) -> float:
    """Threshold producing the desired false positive rate on benign traffic."""
    return float(np.quantile(scores, 1.0 - target_fpr))


def evaluate(
    ranked: np.ndarray,
    y_true: np.ndarray,
    types: np.ndarray,
    label: str,
) -> dict:
    """Evaluate one operating point from the normalized scores.

    Flagged is exactly `ranked >= 0.5`, because normalization places the threshold
    at 0.5 by construction. Deriving it from there instead of scoring everything a
    second time halves the cost of evaluation.
    """
    flagged = ranked >= 0.5

    true_positive = int((flagged & (y_true == 1)).sum())
    false_positive = int((flagged & (y_true == 0)).sum())
    precision = true_positive / max(true_positive + false_positive, 1)

    per_family = {}
    for family in sorted(set(types)):
        if family == "benign":
            continue
        mask = types == family
        subset = ((types == family) | (y_true == 0))
        per_family[family] = {
            "support": int(mask.sum()),
            "recall": float(flagged[mask].mean()),
            "pr_auc": float(
                average_precision_score((types[subset] == family).astype(int), ranked[subset])
            ),
        }

    return {
        "variant": label,
        "pr_auc": float(average_precision_score(y_true, ranked)),
        "roc_auc": float(roc_auc_score(y_true, ranked)),
        "recall": float(flagged[y_true == 1].mean()),
        "precision": float(precision),
        "false_positive_rate": float(flagged[y_true == 0].mean()),
        "false_positives": false_positive,
        "false_negatives": int(y_true.sum()) - true_positive,
        "recall_by_type": per_family,
    }


def operating_points(
    raw: np.ndarray,
    y_true: np.ndarray,
    calibration: dict[float, float],
    groups: list[list[int]],
) -> list[dict]:
    """Operating-point table, for the README and for whoever runs the service.

    The cutoff comes from the calibration table — the same held-out benign slice the
    service uses. Taking the quantile from the test set itself would produce an
    oracle-calibrated curve, optimistic exactly where the decision is made: at 0.05%
    FPR the oracle version promised recall 0.85 where the service delivers 0.56.

    Incident recall is the metric that matters for this architecture. The dossier
    carries the IP's whole window, not only the events above the threshold, so an
    event that escapes is not a lost attack when a sibling in the same window was
    flagged. What is actually lost is the window that produces no dossier at all.
    """
    attack_groups = [g for g in groups if any(y_true[i] == 1 for i in g)]
    table = []
    for target in sorted(calibration):
        flagged = raw >= calibration[target]
        true_positive = int((flagged & (y_true == 1)).sum())
        false_positive = int((flagged & (y_true == 0)).sum())
        dossiers = sum(1 for g in groups if any(flagged[i] for i in g))
        covered = sum(1 for g in attack_groups if any(flagged[i] for i in g))
        # Attack events that end up inside a dossier an agent reads, whether or not
        # they passed the threshold themselves.
        visible = sum(
            sum(1 for i in g if y_true[i] == 1)
            for g in attack_groups
            if any(flagged[i] for i in g)
        )
        table.append(
            {
                "target_fpr": target,
                "threshold": round(float(calibration[target]), 4),
                "event_recall": round(true_positive / max(int(y_true.sum()), 1), 4),
                "incident_recall": round(covered / max(len(attack_groups), 1), 4),
                "incidents_missed": len(attack_groups) - covered,
                "attack_events_visible_to_agent": round(
                    visible / max(int(y_true.sum()), 1), 4
                ),
                "precision": round(
                    true_positive / max(true_positive + false_positive, 1), 4
                ),
                "false_positives": false_positive,
                "false_negatives": int(y_true.sum()) - true_positive,
                "dossiers": dossiers,
            }
        )
    return table


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sample", type=Path, default=Path("data/sample.csv.gz"))
    parser.add_argument("--out", type=Path, default=Path("models/detector.joblib"))
    parser.add_argument("--report", type=Path, default=Path("reports/metrics.json"))
    parser.add_argument("--target-fpr", type=float, default=0.002)
    parser.add_argument("--fit-limit", type=int, default=150_000)
    parser.add_argument("--seed", type=int, default=SEED)
    parser.add_argument(
        "--skip-baselines", action="store_true",
        help="skip the comparison baselines (the supervised one takes ~2 min)",
    )
    args = parser.parse_args()

    print(f"loading {args.sample}")
    events, meta = load_events(args.sample)
    labels = meta["label"].to_numpy()
    types = meta["type"].to_numpy()
    print(f"events: {len(events):,}  attacks: {int(labels.sum()):,} ({labels.mean():.3%})")

    train_ips, test_ips = split_ips_by_type(meta, args.seed)
    train_mask = meta["ip"].isin(train_ips).to_numpy()
    test_mask = meta["ip"].isin(test_ips).to_numpy()
    print(
        f"split by IP -> train {train_mask.sum():,} events / {len(train_ips):,} IPs"
        f" | test {test_mask.sum():,} events / {len(test_ips):,} IPs"
    )

    # Fit and calibration use only benign events from training IPs.
    benign_train = [
        event for event, keep, label in zip(events, train_mask, labels) if keep and label == 0
    ][: args.fit_limit]
    rng = np.random.default_rng(args.seed)
    order = rng.permutation(len(benign_train))
    cut = int(len(order) * (1 - CALIBRATION_FRACTION))
    fit_set = [benign_train[i] for i in order[:cut]]
    calibration_set = [benign_train[i] for i in order[cut:]]

    print(
        f"\nfitting on {len(fit_set):,} benign URLs"
        f" | calibrating the threshold on {len(calibration_set):,} held out"
    )
    print("no attack event and no positive label enters the fit")

    url_model = UrlNoveltyModel().fit([event.decoded_url for event in fit_set])
    agent_model = UrlNoveltyModel().fit([event.user_agent for event in fit_set])

    url_calibration_scores = np.array(
        [url_model.score(event.decoded_url) for event in calibration_set]
    )
    agent_calibration_scores = np.array(
        [agent_model.score(event.user_agent) for event in calibration_set]
    )

    # Table of thresholds for several operating points, stored in the artifact.
    # Moving the operating point no longer requires retraining: the choice depends
    # on how much triage work the operation tolerates.
    rates = (0.0002, 0.0005, 0.001, 0.002, 0.005, 0.01)
    calibration_table = {
        rate: calibrate(url_calibration_scores, rate) for rate in rates
    }
    url_threshold = calibration_table[args.target_fpr]
    agent_threshold = calibrate(agent_calibration_scores, args.target_fpr)
    print(f"URL threshold {url_threshold:.4f} | user-agent threshold {agent_threshold:.4f}")

    test_events = [event for event, keep in zip(events, test_mask) if keep]
    y_test = labels[test_mask]
    types_test = types[test_mask]

    # Raw scores, computed once and reused everywhere.
    raw_url = np.array([url_model.score(event.decoded_url) for event in test_events])
    raw_agent = np.array([agent_model.score(event.user_agent) for event in test_events])

    print("\nevaluating variants")
    # The disjunctive variant flags when either field passes its own threshold; on
    # the normalized scale that is the maximum of the two ratios.
    ranked_url = np.minimum(raw_url / url_threshold / 2.0, 0.999)
    ranked_both = np.minimum(
        np.maximum(raw_url / url_threshold, raw_agent / agent_threshold) / 2.0, 0.999
    )
    url_only = evaluate(ranked_url, y_test, types_test, "url_only")
    with_agent = evaluate(ranked_both, y_test, types_test, "url_and_user_agent")

    for name, result in (("URL only", url_only), ("URL + user agent", with_agent)):
        print(
            f"  {name:<18} recall {result['recall']:.4f}  precision {result['precision']:.4f}"
            f"  PR-AUC {result['pr_auc']:.4f}  FP {result['false_positives']}"
        )

    # Selection by F1, not by recall. Recall alone would always pick the
    # disjunctive rule, which by construction flags more — including more false
    # positives, which is what consumes the LLM budget afterwards.
    def f1(result: dict) -> float:
        precision, recall = result["precision"], result["recall"]
        return 2 * precision * recall / max(precision + recall, 1e-9)

    chosen = "url_and_user_agent" if f1(with_agent) > f1(url_only) else "url_only"
    print(
        f"\nF1 URL only {f1(url_only):.4f} | F1 URL + user agent {f1(with_agent):.4f}"
        f"\nselected variant: {chosen}"
    )
    if chosen != "url_only":
        raise SystemExit(
            "the user-agent variant won; the service only implements url_only.\n"
            "Reintroduce the second field in NoveltyDetector before proceeding."
        )

    detector = NoveltyDetector(url_model, url_threshold, calibration_table)

    # Incident recall needs the same grouping the service uses in production.
    groups = list(group_by_ip_window(test_events).values())

    report = {
        "approach": "novelty detection (char n-gram LM fitted on benign traffic only)",
        "trained_at": datetime.now(timezone.utc).isoformat(),
        "dataset": {
            "events": len(events),
            "attacks": int(labels.sum()),
            "attack_rate": float(labels.mean()),
            "train_events": int(train_mask.sum()),
            "test_events": int(test_mask.sum()),
            "train_ips": len(train_ips),
            "test_ips": len(test_ips),
            "type_counts": meta["type"].value_counts().to_dict(),
        },
        "training": {
            "fit_urls": len(fit_set),
            "calibration_urls": len(calibration_set),
            "labels_used_in_fit": False,
            "target_fpr": args.target_fpr,
            "url_threshold": url_threshold,
            "agent_threshold": agent_threshold,
            "variant": chosen,
        },
        "novelty_url_only": url_only,
        "novelty_url_and_user_agent": with_agent,
        "operating_points": operating_points(
            raw_url, y_test, calibration_table, groups
        ),
        "windows": {
            "total": len(groups),
            "with_attack": sum(
                1 for g in groups if any(y_test[i] == 1 for i in g)
            ),
        },
    }

    if not args.skip_baselines:
        print("\nevaluating comparison baselines (evidence for the pivot)")
        train_events = [event for event, keep in zip(events, train_mask) if keep]
        report["baseline_regex"] = regex_baseline(test_events, y_test)
        report["baseline_supervised"] = supervised_baseline(
            train_events, labels[train_mask], test_events, y_test
        )
        for name in ("baseline_regex", "baseline_supervised"):
            values = report[name]
            print(
                f"  {name:<22} recall {values['recall']:.4f}"
                f"  precision {values['precision']:.4f}  FP {values['false_positives']}"
            )

    artifact = {
        "detector": detector,
        "metadata": {
            "approach": report["approach"],
            "trained_at": report["trained_at"],
            "target_fpr": args.target_fpr,
            "variant": chosen,
            "sample": str(args.sample),
            "seed": args.seed,
        },
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(artifact, args.out, compress=3)
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, indent=2, ensure_ascii=False))

    print(f"\nmodel saved to {args.out} ({args.out.stat().st_size / 1e6:.1f} MB)")
    print(f"report saved to {args.report}\n")
    print(f"event recall   {url_only['recall']:.4f}")
    print(f"precision      {url_only['precision']:.4f}")
    print(f"PR-AUC         {url_only['pr_auc']:.4f}   ROC-AUC {url_only['roc_auc']:.4f}")
    print(f"FPR            {url_only['false_positive_rate']:.4%}")
    print("\nrecall by family (all zero-shot — the model never saw an attack):")
    for family, values in url_only["recall_by_type"].items():
        print(
            f"  {family:<10} recall {values['recall']:.3f}  "
            f"PR-AUC {values['pr_auc']:.3f}  (n={values['support']})"
        )

    print("\noperating points (threshold from the calibration slice, not the test set):")
    print(f"  {'FPR':>7} {'ev.recall':>10} {'inc.recall':>11} {'missed':>7} "
          f"{'precision':>10} {'dossiers':>9}")
    for point in report["operating_points"]:
        mark = " <- default" if point["target_fpr"] == args.target_fpr else ""
        print(
            f"  {point['target_fpr']:>7.4f} {point['event_recall']:>10.4f} "
            f"{point['incident_recall']:>11.4f} {point['incidents_missed']:>7} "
            f"{point['precision']:>10.4f} {point['dossiers']:>9,}{mark}"
        )
    print(
        f"\nwindows (IP, 5min) in the test set: {report['windows']['total']:,}"
        f" | containing an attack: {report['windows']['with_attack']}"
    )


if __name__ == "__main__":
    main()
